force-app/main/default/objects/Consultant__c/Consultant__c.object-meta.xml
<CustomObject>
    <label>Consultant</label>
    <nameField>
        <label>Consultant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consultants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultant__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Project_Manager__r.Id</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Consultants</relationshipLabel>
    <relationshipName>Consultants</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consultant__c/fields/Role_in_Project__c.field-meta.xml
<CustomField>
    <fullName>Role_in_Project__c</fullName>
    <label>Role in Project</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Role_in_Project</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Pricing__c/Project_Pricing__c.object-meta.xml
<CustomObject>
    <label>Project Pricing</label>
    <nameField>
        <label>Project Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Pricings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Pricing__c/fields/Consultant_rate__c.field-meta.xml
<CustomField>
    <fullName>Consultant_rate__c</fullName>
    <label>Consultant rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Pricing__c/fields/Pricing_Unit__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Unit__c</fullName>
    <label>Pricing Unit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hourly</fullName>
                <default>true</default>
                <label>Hourly</label>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Pricing__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Pricings</relationshipLabel>
    <relationshipName>Project_Pricings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Pricing__c/fields/Role_In_Project__c.field-meta.xml
<CustomField>
    <fullName>Role_In_Project__c</fullName>
    <label>Role In Project</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Role_in_Project</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ConsultantTriggerHandler.cls
public class ConsultantTriggerHandler {

    
    public static void checkIfProjectPricingExist(List<Consultant__c> consultantList){
        Set<Id> project=new Set<Id>();
        
        for(Consultant__c con:consultantList){
            project.add(con.Project__c);
           
        }
       Map<String,Decimal> mapOfProRoleAndCurrency=new  Map<String,Decimal>();
            for(Project_Pricing__c pp:[Select Consultant_rate__c,Pricing_Unit__c,Project__c,Role_In_Project__c
                                       from Project_Pricing__c
                                       Where Project__c=:project] ){
                                           mapOfProRoleAndCurrency.put(pp.Project__c+'-'+pp.Role_In_Project__c,pp.Consultant_rate__c);
                                       }
        for(Consultant__c con:consultantList){
            if(!mapOfProRoleAndCurrency.containsKey(con.Project__c+'-'+con.Role_in_Project__c)){
                con.addError('No Pricing Defined for this role in Project, Please use project pricing to define price for the consultant role');
            }
        }
    }
}