force-app/main/default/objects/Consultant__c/Consultant__c.object-meta.xml
<CustomObject>
    <label>Consultant</label>
    <nameField>
        <label>Consultant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consultants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultant__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Consultants</relationshipLabel>
    <relationshipName>Consultants</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consultant__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Project_Manager__r.Id</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Consultants</relationshipLabel>
    <relationshipName>Consultants</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consultant__c/fields/Role_in_Project__c.field-meta.xml
<CustomField>
    <fullName>Role_in_Project__c</fullName>
    <label>Role in Project</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Role_in_Project</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultant__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>start Date when employee is assigned the project</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectDashboardController.cls
public with sharing class ProjectDashboardController {
    // public class ProjectAndConsultantWrapper{
    //     @AuraEnabled
    //     public String projectName;
    //     @AuraEnabled
    //     public String projectId;
    //     @AuraEnabled
    //     public List<Consultant__c> consultantList;
    // }
    @AuraEnabled(cacheable=true)
    public static List<Employee__c> listOfEmployeeInFreePool(){
        try {
            Set<Id> setOfConultants=new Set<Id>();
            for(Consultant__c con:[Select Id,Employee__c from Consultant__c Where End_Date__c=null]){
                setOfConultants.add(con.Employee__c);
            }
            List<Employee__c> listOfEmployee=[Select Id,Name,Skills__c from Employee__c Where Id Not in :setOfConultants];

            return listOfEmployee;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled(cacheable=true)
    public static Map<String,List<Consultant__c>> getProjectsAssignedToManager(){
        try {
            Map<String,List<Consultant__c>> mapOfConAndProject=new Map<String,List<Consultant__c>>();
            for(Consultant__c con:[Select Employee__r.Name,Project__c,Project__r.Name, Start_Date__c,Role_in_Project__c
            from Consultant__c
            Where Project__r.Project_Manager__c=:UserInfo.getUserId() ]){
                List<Consultant__c> listOfCon=new List<Consultant__c>();
                if(mapOfConAndProject.containsKey(con.Project__c+'-'+con.Project__r.Name)){
                    listOfCon=mapOfConAndProject.get(con.Project__c+'-'+con.Project__r.Name);
                    listOfCon.add(con);
                    mapOfConAndProject.put(con.Project__c+'-'+con.Project__r.Name,listOfCon);
                }else{
                    listOfCon.add(con);
                    mapOfConAndProject.put(con.Project__c+'-'+con.Project__r.Name,listOfCon);
                }
            }
            List<Project__c> listOfPro=[Select Id,Name from Project__c Where Project_Manager__c=:UserInfo.getUserId() ];
            if(listOfPro.size()>0){
                for(Project__c project:listOfPro){
                    if(!mapOfConAndProject.containsKey(project.Id+'-'+project.Name)){
                        mapOfConAndProject.put(project.Id+'-'+project.Name,new List<Consultant__c>());
                    }
                }
            }
            return mapOfConAndProject;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}